### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jhgsbgj** [safemine/SafeMineCore#1]
addnode=?

**Comment by safemine** [comment]
> addnode=?

Hey jhgsbgj, here's a current list of addnodes= that you can add to your SafeMine config in the AppData folder. Just place these in the safemine.conf there and reboot your wallet.

addnode=18.117.231.170
addnode=45.79.68.40
addnode=45.79.173.155
addnode=157.97.171.169
addnode=3.135.214.35
addnode=192.155.94.193

Next update we should hopefully have it where you don't require to manually add these, hope that helps. If you have any issues further just let us know.

**Comment by jhgsbgj** [comment]
ann
